packages:
  remote_package:
    url: https://github.com/dyrvigk/nilan
    ref: main
    files: [components/nilan/comfort.yaml]
    refresh: 0s

sensor:
#########################
#### INPUT REGISTERS ####
#########################
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Fresh air intake T1 temperature"
    id: nilan_intake_temp_t1
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 201
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Afkast T4 temperature"
    id: nilan_outlet_temp_t7
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 204
    filters:
      - multiply: 0.01    

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Inlet (before heater) T2 temperature"
    id: nilan_inlet_temp_t2
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 202
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Condenser T5 temperature"
    id: nilan_condenser_temp_t5
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 205
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Evaporator T6 temperature"
    id: nilan_evap_temp_t6
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 206
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot weater top T11 temperature"
    id: nilan_top_temp_t11
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 211
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot water bottom T12 temperature"
    id: nilan_bottom_temp_t12
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 212
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T13"
    id: nilan_return_temp_t13
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 213
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T14"
    id: nilan_supply_temp_t14
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 214
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "HeatPump Return T16"
    id: nilan_heatpump_return_temp_t16
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 1901
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "HeatPump Supply T17"
    id: nilan_heatpump_supply_temp_t17
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 1900
    filters:
      - multiply: 0.1   

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "HeatPump Ambient T20"
    id: nilan_heatpump_ambient_temp_t20
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 1903
    filters:
      - multiply: 0.1    

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "HeatPump BufferTank T18"
    id: nilan_heatpump_buffertank_temp_t18
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 6169
    filters:
      - multiply: 0.1   

      
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "HeatPump Cold Side return T13"
    id: nilan_heatpump_cold_side_return_t13
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 6171
    filters:
      - multiply: 0.1   

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heatpump Prespipe T35"
    id: nilan_heatpump_prespipe_temp_t35
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 6173
    filters:
      - multiply: 0.1 
      
  


binary_sensor:
#########################
#### INPUT REGISTERS ####
#########################
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot water boiling"
    id: nilan_hot_water_boiling
    register_type: read
    address: 109

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot water 3-way valve position"
    id: nilan_3_way_position
    register_type: read
    address: 110

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hotgas defrost"
    id: nilan_hotgas_defrost
    register_type: read
    address: 111

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Defrost termostat"
    id: nilan_defrost_termostat
    register_type: read
    address: 112

###########################
#### HOLDING REGISTERS ####
###########################
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air flap"
    id: nilan_air_flap
    register_type: holding
    address: 100

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Smoke flap"
    id: nilan_smoke_flap
    register_type: holding
    address: 101

  - platform: template
    id: nilan_bypass_state
    name: Bypass state
    device_class: opening
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    id: nilan_bypass_open_request
    register_type: holding
    address: 102
    on_state: 
    - lambda: !lambda |-
        id(nilan_bypass_state).publish_state(true);
        
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    id: nilan_bypass_close_request
    register_type: holding
    address: 103
    on_state: 
    - lambda: !lambda |-
        id(nilan_bypass_state).publish_state(false);
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air heat circulation pump"
    id: nilan_air_heat_circulation_pump
    register_type: holding
    address: 104
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air heating selected"
    id: nilan_air_heat_selected
    register_type: holding
    address: 105
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Compressor"
    id: nilan_compressor
    register_type: holding
    address: 109

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Compressor 2"
    id: nilan_compressor_2
    register_type: read
    address: 1920 
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air condenser active"
    id: nilan_air_condenser_active
    register_type: holding
    address: 114 

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air condenser inactive"
    id: nilan_air_condenser_inactive
    register_type: holding
    address: 115 

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "External radiator heat "
    id: nilan_external_radiator_heat 
    register_type: holding
    address: 122   

number:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heatpump Hotwater set"
    id: nilan_heatpump_hotwater_set
    min_value: 5.0
    max_value: 70.0
    step: 1.0
    address: 1822
    force_new_range: true
    use_write_multiple: true
    multiply: 10
  
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "heatpump Hotwater Neutral Zone"
    id: nilan_heatpump_hotater_neutral_zone_set
    min_value: 0.1
    max_value: 15.0
    step: 0.1
    address: 1823
    force_new_range: true
    use_write_multiple: true
    multiply: 10

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heatpump Heating Neutral Zone"
    id: nilan_heatpump_heating_neutral_zone_set
    min_value: 0.1
    max_value: 15.0
    step: 0.1
    address: 1833
    force_new_range: true
    use_write_multiple: true
    multiply: 10

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heatpump Stop Temp"
    id: nilan_heatpump_stop_temp_set
    min_value: 30.0
    max_value: 70.0
    step: 1.0
    address: 6537
    force_new_range: true
    use_write_multiple: true
    multiply: 10
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heatpump Outdoor temp stop"
    id: nilan_heatpump_outdoor_temp_stop_set
    min_value: 45.0
    max_value: 10.0
    step: 1.0
    address: 6538
    force_new_range: true
    use_write_multiple: true
    multiply: 10

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heatpump Total Stop Temp"
    id: nilan_heatpump_total_stop_temp_set    
    min_value: 30.0
    max_value: 90.0
    step: 1.0
    address: 6539
    force_new_range: true
    use_write_multiple: true
    multiply: 10
    

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heatpump Cool Setpoint Min"
    id: nilan_heatpump_cool_setpoint_min
    min_value: 5.0
    max_value: 50.0
    step: 1.0
    address: 6561
    force_new_range: true
    use_write_multiple: true
    multiply: 10
    

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heatpump Heating Setpoint Min"
    id: nilan_heatpump_Heating_setpoint_min
    min_value: 0.0
    max_value: 70.0
    step: 1.0
    address: 6562
    force_new_range: true
    use_write_multiple: true
    multiply: 10

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heatpump Heating Setpoint Max"
    id: nilan_heatpump_heating_setpoint_max
    min_value: 0.0
    max_value: 70.0
    step: 1.0
    address: 6564
    force_new_range: true
    use_write_multiple: true
    multiply: 10
    

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heatpump Evaporator Min"
    id: nilan_heatpump_evaporator_min_temp
    min_value: 45.0
    max_value: 5.0
    step: 1.0
    address: 6564
    force_new_range: true
    use_write_multiple: true
    multiply: 10


text_sensor:

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Heatpump Control mode"
    id: nilan_heatpump_state
    register_type: read
    address: 1931
    lambda: !lambda |-
      uint16_t int_mode = (data[item->offset] << 8) + data[item->offset+1];
      ESP_LOGD("main","Parsed operation mode int : %d", int_mode);
      std::string mode_str;
      switch (int_mode) {
        case 0:  mode_str = "Off"; break;
        case 1:  mode_str = "Ready"; break;
        case 2:  mode_str = "Hot Water Startup"; break;
        case 3:  mode_str = "Hot Water"; break;
        case 4:  mode_str = "Heating Startup"; break;
        case 5:  mode_str = "Heating"; break;
        case 6:  mode_str = "Heatpump Stop"; break;
        case 7:  mode_str = "El Heating"; break;
        case 8:  mode_str = "El Hot Water"; break;
        case 9:  mode_str = "Forced Cold Pump"; break;
        case 10: mode_str = "Heatpump Stop"; break;
        case 11: mode_str = "Defrost"; break;
        case 12: mode_str = "Air Defrost"; break;
        case 13: mode_str = "Hotgas Defrost"; break;
        case 14: mode_str = "Drip Delay"; break;
        case 15: mode_str = "Hot Water + Heatpump Stop"; break;
        case 16: mode_str = "Heating + Heatpump Stop"; break;
        case 17: mode_str = "Stop"; break;
        case 18: mode_str = "Heating + Heatpump Stop"; break;
        case 19: mode_str = "Hot Water + Heatpump Stop"; break;
        case 20: mode_str = "Pump Exercise"; break;
        case 21: mode_str = "Forced Startup"; break;
        case 22: mode_str = "Forced Running"; break;
        case 23: mode_str = "Forced Running"; break;
        case 24: mode_str = "Forced Running Heatpump Stop"; break;
        case 25: mode_str = "Manual"; break;
        case 26: mode_str = "Cooling Start"; break;
        case 27: mode_str = "Cooling"; break;
        case 28: mode_str = "Ext Stop"; break;
        case 29: mode_str = "Forced Low Speed"; break;
        default: mode_str = "Default"; break;
      }
      return mode_str;
