external_components:
  - source: github://dyrvigk/nilan@main
    refresh: 0s
    
nilan:
    
select:
      
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Set operation mode"
    id: nilan_set_operation_mode
    address: 70
    value_type: U_WORD
    optionsmap:
      "Off" : 0
      "Auto" : 1


sensor:

#########################
#### INPUT REGISTERS ####
#########################

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Outlet temperature"
    id: nilan_outlet_temp_t4
    unit_of_measurement: 째C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    value_type: S_WORD
    address: 30
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Inlet temperature"
    id: nilan_inlet_temp_t2
    unit_of_measurement: 째C
    accuracy_decimals: 1
    register_type: read
    value_type: S_WORD
    address: 28
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Outdoor temperature"
    id: nilan_outdoor_temp_t1
    unit_of_measurement: 째C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    value_type: S_WORD
    address: 27
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Exhaust temperature"
    id: nilan_exhaust_temp_t3
    unit_of_measurement: 째C
    accuracy_decimals: 1
    device_class: temperature
    register_type: read
    value_type: S_WORD
    address: 29
    filters:
      - multiply: 0.1
      
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Humidity"
    id: nilan_humidity
    unit_of_measurement: '%'
    accuracy_decimals: 1
    device_class: humidity
    register_type: read
    address: 31
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Active alarms"
    id: nilan_active_alarms
    accuracy_decimals: 0
    register_type: read
    address: 50

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Alarm list 1 id"
    id: nilan_alarm_list_1_id
    accuracy_decimals: 0
    register_type: read
    address: 51

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Alarm list 1 info"
    id: nilan_alarm_list_1_info
    accuracy_decimals: 0
    register_type: read
    address: 56
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Alarm list 2 id"
    id: nilan_alarm_list_2_id
    accuracy_decimals: 0
    register_type: read
    address: 52

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Alarm list 2 info"
    id: nilan_alarm_list_2_info
    accuracy_decimals: 0
    register_type: read
    address: 57

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Alarm list 3 id"
    id: nilan_alarm_list_3_id
    accuracy_decimals: 0
    register_type: read
    address: 53

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Alarm list 3 info"
    id: nilan_alarm_list_3_info
    accuracy_decimals: 0
    register_type: read
    address: 58
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Actual fan step"
    id: nilan_actual_fan_step
    accuracy_decimals: 0
    register_type: read
    address: 63               

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Days to next filter change"
    id: nilan_days_to_next_filter_alarm
    unit_of_measurement: 'days'
    accuracy_decimals: 0
    register_type: read
    address: 110    

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Exhaust fan speed"
    id: nilan_exhaust_fan_speed
    unit_of_measurement: '%'
    icon: "mdi:percent"
    accuracy_decimals: 1
    register_type: read
    address: 24
    filters:
      - multiply: 0.1    
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Inlet fan speed"
    id: nilan_inlet_fan_speed
    unit_of_measurement: '%'
    icon: "mdi:percent"
    accuracy_decimals: 1
    register_type: read
    address: 25
    filters:
      - multiply: 0.1    
          
###########################
#### HOLDING REGISTERS ####
###########################


binary_sensor:
#########################
#### INPUT REGISTERS ####
#########################

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air filter alarm"
    id: nilan_filter_alarm
    register_type: read
    address: 49
    bitmask: 1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Bypass damper status"
    id: nilan_bypass_damper
    register_type: read
    address: 23
    bitmask: 1

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Summer mode"
    id: nilan_is_summer
    register_type: read
    address: 72
    bitmask: 0

###########################
#### HOLDING REGISTERS ####
###########################


text_sensor:
  
  - platform: template
    name: "Air filter alarm status"
    lambda: |-
      if (id(nilan_filter_alarm).state) {
        return {"Skift filter"};
      } else {
        return {"Filter OK"};
      }  

  - platform: template
    name: "Bypass damper status"
    lambda: |-
      if (id(nilan_filter_alarm).state) {
        return {"Bypass Open"};
      } else {
        return {"Bypass Closed"};
      }     
number:
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Ventilation speed set"
    id: nilan_ventilation_speed_set
    min_value: 1
    max_value: 4
    step: 1.0
    address: 69 

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Temperature set"
    id: nilan_target_temperature_set
    min_value: 10
    max_value: 30
    step: 1.0
    address: 37
    multiply: 10
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Timeout high level humidity"
    id: nilan_timeout_high_level_humidity_set
    min_value: 0
    max_value: 180
    step: 1.0
    address: 34
   

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Days between filter change"
    id: nilan_days_between_filter_change_set
    min_value: 0
    max_value: 360
    step: 1.0
    address: 50
   
    
    

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "User function 1 ventilation speed set"
    id: nilan_userfct1_ventilation_speed_set
    min_value: 0.0
    max_value: 4.0
    step: 1.0
    address: 79 
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "User function 2 ventilation speed set"
    id: nilan_userfct2_ventilation_speed_set
    min_value: 0.0
    max_value: 4.0
    step: 1.0
    address: 85
 
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "User function 1 time set (minutes)"
    id: nilan_userfct1_time_set
    value_type: U_WORD
    min_value: 1.0
    max_value: 180.0
    step: 1.0
    address: 71

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "User function 2 time set (minutes)"
    id: nilan_userfct2_time_set
    value_type: U_WORD
    min_value: 1.0
    max_value: 180.0
    step: 1.0
    address: 84     

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Supply Air level 1"
    id: nilan_supply_level1
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 59
    multiply: 10   
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Supply Air level 2"
    id: nilan_supply_level2
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 60
    multiply: 10
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Supply Air level 3"
    id: nilan_supply_level3
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 61
    multiply: 10 
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Supply Air level 4"
    id: nilan_supply_level4
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 62
    multiply: 10

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Extract Air level 1"
    id: nilan_extract_level1
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 63
    multiply: 10
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Extract Air level 2"
    id: nilan_extract_level2
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 64
    multiply: 10
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Extract Air level 3"
    id: nilan_extract_level3
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 65
    multiply: 10
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Extract Air level 4"
    id: nilan_extract_level4
    min_value: 20
    max_value: 100
    unit_of_measurement: '%'
    icon: "mdi:percent"
    address: 66
    multiply: 10
    
switch:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Reset filter timer"
    id: nilan_filter_reset
    register_type: holding
    bitmask: 1
    address: 51
 
  - platform: gpio
    pin: ${user_function_1_output}
    name: "Brugervalg 1"   
    id: nilan_user_function2_switch
      
  - platform: gpio
    pin: ${user_function_2_output}
    name: "Brugervalg 2"   
    id: nilan_user_funtion2_switch      
    
climate:
  - platform: nilan
    name: Nilan
    current_temp_sensor_id: nilan_inlet_temp_t2
    target_temp_sensor_id: nilan_target_temperature_set
    fan_speed_sensor_id: nilan_ventilation_speed_set
    mode_select_id: nilan_set_operation_mode
