packages:
  remote_package:
    url: https://github.com/dyrvigk/nilan
    ref: main
    files: [components/nilan/comfort.yaml]
    refresh: 0s

sensor:
#########################
#### INPUT REGISTERS ####
#########################
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Fresh air intake T1 temperature"
    id: nilan_intake_temp_t1
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 201
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Afkast T4 temperature"
    id: nilan_outlet_temp_t7
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 204
    filters:
      - multiply: 0.01    

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Inlet (before heater) T2 temperature"
    id: nilan_inlet_temp_t2
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 202
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Condenser T5 temperature"
    id: nilan_condenser_temp_t5
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 205
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Evaporator T6 temperature"
    id: nilan_evap_temp_t6
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 206
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot weater top T11 temperature"
    id: nilan_top_temp_t11
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 211
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot water bottom T12 temperature"
    id: nilan_bottom_temp_t12
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 212
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T13"
    id: nilan_return_temp_t13
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 213
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T14"
    id: nilan_supply_temp_t14
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 214
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T16"
    id: nilan_before_kondensator_temp_t16
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 216
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T0"
    id: nilan_after_kondensator_temp_t17
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 200
    filters:
      - multiply: 0.01   

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T3"
    id: nilan_buffertank_temp_t18
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 203
    filters:
      - multiply: 0.01    

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T20"
    id: nilan_outdoor_temp_t20
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 220
    filters:
      - multiply: 0.01   

      
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T8"
    id: nilan_t8_temp_t8
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 208
    filters:
      - multiply: 0.01   

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "T9"
    id: nilan_t9_temp_t9
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 208
    filters:
      - multiply: 0.01       
  
  
# NOT WORKING ON COMFORT MODEL
#  - platform: modbus_controller
#    modbus_controller_id: nilan_modbus_controller
#    name: "Actual inlet fan step"
#    id: nilan_actual_inlet_fan_step
#    unit_of_measurement: 'days'
#    accuracy_decimals: 0
#    register_type: read
#    address: 1101

# NOT WORKING ON COMFORT MODEL
#  - platform: modbus_controller
#    modbus_controller_id: nilan_modbus_controller
#    name: "Actual exhaust fan step"
#    id: nilan_actual_exhaust_fan_step
#    unit_of_measurement: 'days'
#    accuracy_decimals: 0
#    register_type: read
#    address: 1102
      
###########################
#### HOLDING REGISTERS ####
###########################

binary_sensor:
#########################
#### INPUT REGISTERS ####
#########################
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot water boiling"
    id: nilan_hot_water_boiling
    register_type: read
    address: 109

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hot water 3-way valve position"
    id: nilan_3_way_position
    register_type: read
    address: 110

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Hotgas defrost"
    id: nilan_hotgas_defrost
    register_type: read
    address: 111

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Defrost termostat"
    id: nilan_defrost_termostat
    register_type: read
    address: 112

###########################
#### HOLDING REGISTERS ####
###########################
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air flap"
    id: nilan_air_flap
    register_type: holding
    address: 100

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Smoke flap"
    id: nilan_smoke_flap
    register_type: holding
    address: 101

  - platform: template
    id: nilan_bypass_state
    name: Bypass state
    device_class: opening
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    id: nilan_bypass_open_request
    register_type: holding
    address: 102
    on_state: 
    - lambda: !lambda |-
        id(nilan_bypass_state).publish_state(true);
        
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    id: nilan_bypass_close_request
    register_type: holding
    address: 103
    on_state: 
    - lambda: !lambda |-
        id(nilan_bypass_state).publish_state(false);
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air heat circulation pump"
    id: nilan_air_heat_circulation_pump
    register_type: holding
    address: 104
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air heating selected"
    id: nilan_air_heat_selected
    register_type: holding
    address: 105
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Compressor"
    id: nilan_compressor
    register_type: holding
    address: 109

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Compressor 2"
    id: nilan_compressor_2
    register_type: holding
    address: 110 
    
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air condenser active"
    id: nilan_air_condenser_active
    register_type: holding
    address: 114 

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Air condenser inactive"
    id: nilan_air_condenser_inactive
    register_type: holding
    address: 115 

  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "External radiator heat "
    id: nilan_external_radiator_heat 
    register_type: holding
    address: 122   

  

#text_sensor:

#######################################################################      
#### WARNING - IF THERE ARE ANY SPECIAL CHARACTERS ON THE DISPLAY, ####
#### ENABLING THESE SENSORS WILL CRASH THE PROGRAM WHEN PUBLISHING ####
#######################################################################
#  - platform: modbus_controller
#    modbus_controller_id: nilan_modbus_controller
#    name: "Display upper line"
#    id: nilan_display_upper_line
#    force_new_range: true
#    register_type: read
#    register_count: 4
#    response_size: 8
#    address: 2002
    
#  - platform: modbus_controller
#    modbus_controller_id: nilan_modbus_controller
#    name: "Display lower line"
#    id: nilan_display_lower_line
#    force_new_range: true
#    register_type: read
#    register_count: 4
#    response_size: 8
#    address: 2007
